---
- hosts: all
  become: true

  tasks:

    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

#    - name: Install required system packages
#      apt: name={{ item }} state=latest update_cache=yes
#      loop: ['docker.io', 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip',
#             'virtualenv', 'python3-setuptools',  'python3-docker',]


    - name: Install Docker Module for Python
      pip:
        name: docker

    - name : Create pyATS Container
      docker_container:
        name: pyats_cont2
        image: pyats_exec
        command :
        - /bin/sh
        - sleep infinity
        - touch file2.txt







