---
- hosts: dockerHost2
  become: true

  vars:
    - container_name: pyats_cont

  tasks:

#    - name: Update/Upgrade dependencies
#      apt: update_cache=yes upgrade=yes


#    - name: Install python-apt using apt
#      apt: name=python-apt state=latest update_cache=yes force_apt_get=yes

#    - name: Install aptitude using apt
#      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

#    - name: Install required system packages
#      apt: name={{ item }} state=latest update_cache=yes
#      loop: ['docker.io', 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip',
#             'virtualenv', 'python3-setuptools',  'python3-docker',]


#    - name: Install Docker Module for Python
#      pip: name=docker

#    - name: Uninstall ssl_match_hostname
#      pip: name=python-backports.ssl-match-hostname state=absent

#    - name: Install ssl_match_hostname apt module for Python
#      apt: name=python-backports.ssl-match-hostname state=latest update_cache=yes force_apt_get=yes

    - name: Create pyATS Container
      docker_container:
        name: "{{ container_name }}"
        image: ciscotestautomation/pyats:latest
        stop_timeout: 300
        detach: true
        command:
          - sleep infinity

    - name: update/upgrade dependencies in docker container
      shell: docker exec -it "{{ container_name }}" bash -c "apt-get update -y ; apt-get upgrade -y"

    - name: install Git on docker container
      shell: docker exec -it "{{ container_name }}" apt-get install git -y

    - name: clone pyATs repository to docker container
      shell: docker exec -it "{{ container_name }}" git clone http://github.com/timwijers/pyATS

    - name: update pyATS repo in docker container
      shell: docker exec -it "{{ container_name }}" bash -c "cd /pyats/pyATS ;
             git pull http://github.com/timwijers/pyATS"

    - name: execute configuration file in docker container
      shell: docker exec -it "{{ container_name }}" bash -c "source bin/activate ; cd /pyats/pyATS ;
             pyats run job jobfile.py ; pyats logs view"








