---
- hosts: all
  become: true

  tasks:

    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: ['docker.io', 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip',
             'virtualenv', 'python3-setuptools',  'python3-docker']


    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Pull pyATS Docker image
      docker_image:
        name: ciscotestautomation/pyats:latest
        source: pull

    - name : Create pyATS Container
      docker_container:
        name: pyats_cont1
        image: ciscotestautomation/pyats:latest
        state: started

    - name : execute install script + execute test cases
      script: installscript.sh







