---
- hosts: 127.0.0.1
  become: true

  tasks:

  - name: Cd into correct folder
    shell: cd /etc/ansible/pyATS

  - name: Update Git Repository
    command: git pull http://github.com/timwijers/pyATS

  - name: Create Eve-NG Lab with all required Nodes
    script: "'Configure Eve-ng Labs.py'"

  - name: Extract IP's from the Eve-NG Nodes and create Ansible Hosts file + pyATS Testbed
    script: "'AnsiblePLB_Create_EveLab_ExtractIPS.yml'"