---
- hosts: 127.0.0.1
  become: true

  tasks:

  - name: Cd into correct folder
    shell: cd /etc/ansible/pyATS

  - name: Update Git Repository
    command: git pull http://github.com/timwijers/pyATS

  - name: Create Eve-NG Lab with all required Nodes
    shell: python 'Configure Eve-ng Labs.py'

  - name: Extract IP's from the Eve-NG Nodes and create Ansible Hosts file + pyATS Testbed
    shell: python3 'searchIP_Fill_TB_&_Hosts.py'

  - name: Move Hosts file to ansible directory
    shell: cp /etc/ansible/pyATS/hosts /etc/ansible/hosts