# curl  -X POST -d '{"username":"tim_wijers","password":"Welkom01"}' http://10.100.244.1/api/auth/login
POST http://10.100.244.1/api/auth/login
Content-Type: application/json

{"username":"tim_wijers","password":"Welkom01"}

###

# curl -X POST -d '{"path":"/Tim Wijers/pyATS_TestLabs/","name":"pyATSTestLab_1","version":"1","author":"Tim Wijers","description":"pyATS Test Lab 1","body":"This is a testlab created by the Eve-NG REST API. Intended for pyATS framework testing purposes"}' -H 'Content-type: application/json' http://10.100.244.1/api/labs
POST http://10.100.244.1/api/labs
Content-Type: application/json

{"path":"/Tim Wijers/pyATS_TestLabs/","name":"pyATSTestLab_20","version":"1","author":"Tim Wijers","description":"pyATS Test Lab 20","body":"This is a testlab created by the Eve-NG REST API. Intended for pyATS framework testing purposes"}

###

GET http://10.100.244.1/api/labs/Tim%20Wijers/pyATS_TestLabs/pyATSTestLab.unl/nodes
Content-Type: application/json

###

POST http://10.100.244.1/api/labs/Tim%20Wijers/pyATS_TestLabs/pyATSTestLab.unl/networks
Content-Type: application/json

{"count":"1","visibility":"1","name":"InternetGW","type":"pnet0","left":"349","top":"558","postfix":0}

###