# Title: Eve-NG REST API connection page
# Author: Tim Wijers
# Copyright: Routz B.V.


# curl  -X POST -d '{"username":"tim_wijers","password":"Welkom01"}' http://10.100.244.1/api/auth/login
POST http://10.100.244.1/api/auth/login
Content-Type: application/x-www-form-urlencoded

{"username":"tim_wijers","password":"Welkom01"}

###

# curl -X GET -H 'Content-type: application/json' http://10.100.244.1/api/labs/Tim%20Wijers/pyATS%20testlab.unl
GET http://10.100.244.1/api/labs/Tim%20Wijers/pyATS_TestLabs/PyATS_TestLab_25mei.unl/nodes/5/interfaces


Content-Type: application/json

###

# curl -X GET -H 'Content-type: application/json' http://10.100.244.1/api/labs/Tim%20Wijers/pyATS%20testlab.unl/nodes
DELETE http://10.100.244.1/api/labs/Tim%20Wijers/testlab.unl

Content-Type: application/json

###

DELETE http://10.100.244.1/api/labs/Tim%20Wijers/pyATS_TestLabs/PyATS_TestLab_12052020144421.unl
Content-Type: application/json


###


